DEFAULT_PERMISSIONS: list[dict] = [
    # Workflow
    {"permission_key": "workflow:create",           "category": "workflow"},
    {"permission_key": "workflow:view",             "category": "workflow"},
    {"permission_key": "workflow:update",           "category": "workflow"},
    {"permission_key": "workflow:delete",           "category": "workflow"},
    {"permission_key": "workflow:execute",          "category": "workflow"},
    {"permission_key": "workflow:approve",          "category": "workflow"},
    {"permission_key": "workflow:assign",           "category": "workflow"},
    {"permission_key": "workflow:audit:view",       "category": "workflow"},
    {"permission_key": "workflow:template:create",  "category": "workflow"},
    {"permission_key": "workflow:template:publish", "category": "workflow"},
    # Agent
    {"permission_key": "agent:create",             "category": "agent"},
    {"permission_key": "agent:view",               "category": "agent"},
    {"permission_key": "agent:update",             "category": "agent"},
    {"permission_key": "agent:delete",             "category": "agent"},
    {"permission_key": "agent:approve",            "category": "agent"},
    {"permission_key": "agent:execute",            "category": "agent"},
    {"permission_key": "agent:learning:view",      "category": "agent"},
    {"permission_key": "agent:learning:approve",   "category": "agent"},
    {"permission_key": "agent:learning:rollback",  "category": "agent"},
    # Tool
    {"permission_key": "tool:register",            "category": "tool"},
    {"permission_key": "tool:view",                "category": "tool"},
    {"permission_key": "tool:update",              "category": "tool"},
    {"permission_key": "tool:execute",             "category": "tool"},
    {"permission_key": "tool:approve_execution",   "category": "tool"},
    {"permission_key": "tool:assign_to_agent",     "category": "tool"},
    # Context Fabric
    {"permission_key": "context:session:view",         "category": "context"},
    {"permission_key": "context:message:view",         "category": "context"},
    {"permission_key": "context:summary:view",         "category": "context"},
    {"permission_key": "context:token_savings:view",   "category": "context"},
    {"permission_key": "context:llm_handoff:create",   "category": "context"},
    {"permission_key": "context:memory:view",          "category": "context"},
    # Model Policy
    {"permission_key": "model:use",                "category": "model"},
    {"permission_key": "model:override",           "category": "model"},
    {"permission_key": "model:policy:create",      "category": "model"},
    {"permission_key": "model:policy:update",      "category": "model"},
    {"permission_key": "model:policy:view",        "category": "model"},
    # Capability
    {"permission_key": "capability:create",               "category": "capability"},
    {"permission_key": "capability:view",                 "category": "capability"},
    {"permission_key": "capability:update",               "category": "capability"},
    {"permission_key": "capability:archive",              "category": "capability"},
    {"permission_key": "capability:member:add",           "category": "capability"},
    {"permission_key": "capability:member:remove",        "category": "capability"},
    {"permission_key": "capability:relationship:create",  "category": "capability"},
    {"permission_key": "capability:sharing_grant:create", "category": "capability"},
    {"permission_key": "capability:sharing_grant:approve","category": "capability"},
    {"permission_key": "capability:use_shared",           "category": "capability"},
    # Admin / Audit
    {"permission_key": "role:create",         "category": "admin"},
    {"permission_key": "role:update",         "category": "admin"},
    {"permission_key": "role:assign",         "category": "admin"},
    {"permission_key": "permission:view",     "category": "admin"},
    {"permission_key": "audit:view",          "category": "admin"},
    {"permission_key": "platform:all",        "category": "admin"},
    {"permission_key": "platform:super_admin","category": "admin"},
]
