DEFAULT_ROLES: list[dict] = [
    {
        "role_key": "super_admin",
        "name": "Super Admin",
        "role_scope": "platform",
        "system_role": True,
        "permissions": ["platform:all"],
    },
    {
        "role_key": "platform_admin",
        "name": "Platform Admin",
        "role_scope": "platform",
        "system_role": True,
        "permissions": [
            "capability:create", "capability:view", "capability:update",
            "role:create", "role:update", "role:assign", "permission:view", "audit:view",
        ],
    },
    {
        "role_key": "platform_auditor",
        "name": "Platform Auditor",
        "role_scope": "platform",
        "system_role": True,
        "permissions": [
            "audit:view", "capability:view",
            "context:token_savings:view", "workflow:audit:view",
        ],
    },
    {
        "role_key": "capability_admin",
        "name": "Capability Admin",
        "role_scope": "capability",
        "system_role": True,
        "permissions": [
            "capability:view", "capability:update",
            "capability:member:add", "capability:member:remove",
            "capability:relationship:create", "capability:sharing_grant:create",
            "workflow:create", "workflow:view", "workflow:update", "workflow:execute", "workflow:approve",
            "agent:create", "agent:view", "agent:update", "agent:execute", "agent:learning:approve",
            "tool:register", "tool:view", "tool:execute",
            "context:session:view", "context:token_savings:view",
            "audit:view", "capability:use_shared",
        ],
    },
    {
        "role_key": "workflow_designer",
        "name": "Workflow Designer",
        "role_scope": "capability",
        "system_role": True,
        "permissions": [
            "workflow:create", "workflow:view", "workflow:update",
            "workflow:template:create",
        ],
    },
    {
        "role_key": "workflow_executor",
        "name": "Workflow Executor",
        "role_scope": "capability",
        "system_role": True,
        "permissions": ["workflow:view", "workflow:execute", "context:session:view", "capability:use_shared"],
    },
    {
        "role_key": "workflow_approver",
        "name": "Workflow Approver",
        "role_scope": "capability",
        "system_role": True,
        "permissions": ["workflow:view", "workflow:approve", "audit:view"],
    },
    {
        "role_key": "agent_creator",
        "name": "Agent Creator",
        "role_scope": "capability",
        "system_role": True,
        "permissions": ["agent:create", "agent:view", "agent:update"],
    },
    {
        "role_key": "agent_operator",
        "name": "Agent Operator",
        "role_scope": "capability",
        "system_role": True,
        "permissions": ["agent:view", "agent:execute", "context:llm_handoff:create", "tool:execute"],
    },
    {
        "role_key": "tool_admin",
        "name": "Tool Admin",
        "role_scope": "capability",
        "system_role": True,
        "permissions": [
            "tool:register", "tool:view", "tool:update",
            "tool:assign_to_agent", "tool:approve_execution",
        ],
    },
    {
        "role_key": "tool_executor",
        "name": "Tool Executor",
        "role_scope": "capability",
        "system_role": True,
        "permissions": ["tool:view", "tool:execute"],
    },
    {
        "role_key": "auditor",
        "name": "Auditor",
        "role_scope": "capability",
        "system_role": True,
        "permissions": [
            "workflow:view", "workflow:audit:view", "audit:view",
            "context:token_savings:view", "context:session:view",
        ],
    },
    {
        "role_key": "viewer",
        "name": "Viewer",
        "role_scope": "capability",
        "system_role": True,
        "permissions": ["workflow:view", "agent:view", "context:token_savings:view"],
    },
]
