"""M74 Phase 1B — path-coverage helper tests.

Pure-function tests of ``check_path_coverage``. The integration with
``loop.py`` is covered by test_governed_loop.py's existing fixtures
once we extend them; these tests pin the helper's semantics in
isolation so refactors of the loop don't drift the contract.
"""
from __future__ import annotations

from context_api_service.app.governed.path_coverage import (
    CoverageGap,
    check_path_coverage,
)


# ── happy paths ─────────────────────────────────────────────────────────────


def test_no_plan_means_no_check():
    """Stages without a prior PlanReceipt (None or no target_files) are
    vacuously covered — there's nothing to contradict."""
    edit = {"kind": "edit_receipt", "edits": [{"file": "a.py", "edit_type": "apply_patch", "reason": "x"}]}
    assert check_path_coverage(None, edit) is None
    assert check_path_coverage({}, edit) is None
    assert check_path_coverage({"target_files": []}, edit) is None


def test_full_coverage_returns_none():
    """All plan targets edited → coverage satisfied."""
    plan = {"target_files": ["src/a.py", "src/b.py"]}
    edit = {
        "edits": [
            {"file": "src/a.py", "edit_type": "apply_patch", "reason": "fix x"},
            {"file": "src/b.py", "edit_type": "replace_text", "reason": "fix y"},
        ],
    }
    assert check_path_coverage(plan, edit) is None


def test_over_coverage_is_fine():
    """Editing files NOT in the plan (legitimate discovery) is allowed.
    Only UNDER-coverage is refused."""
    plan = {"target_files": ["src/a.py"]}
    edit = {
        "edits": [
            {"file": "src/a.py", "edit_type": "apply_patch", "reason": "fix x"},
            {"file": "src/helper.py", "edit_type": "create_file", "reason": "extracted helper"},
        ],
    }
    assert check_path_coverage(plan, edit) is None


def test_skipped_targets_count_as_coverage():
    """An explicit skip with a reason satisfies coverage for that file."""
    plan = {"target_files": ["src/a.py", "src/b.py", "src/c.py"]}
    edit = {
        "edits": [{"file": "src/a.py", "edit_type": "apply_patch", "reason": "fix x"}],
        "skipped_targets": [
            {"file": "src/b.py", "reason": "auto-regenerated by build"},
            {"file": "src/c.py", "reason": "deferred to follow-up issue"},
        ],
    }
    assert check_path_coverage(plan, edit) is None


def test_skipped_and_edited_same_file_is_fine():
    """Edit wins when a file appears in both lists — the skip is a soft
    declaration the actual edit superseded."""
    plan = {"target_files": ["src/a.py"]}
    edit = {
        "edits": [{"file": "src/a.py", "edit_type": "apply_patch", "reason": "fix x"}],
        "skipped_targets": [{"file": "src/a.py", "reason": "originally thought N/A"}],
    }
    assert check_path_coverage(plan, edit) is None


# ── refusal paths ───────────────────────────────────────────────────────────


def test_uncovered_target_refused():
    """Plan says A+B+C, edit touches A only, no skips → refuse with B+C."""
    plan = {"target_files": ["src/a.py", "src/b.py", "src/c.py"]}
    edit = {
        "edits": [{"file": "src/a.py", "edit_type": "apply_patch", "reason": "fix x"}],
    }
    gap = check_path_coverage(plan, edit)
    assert isinstance(gap, CoverageGap)
    assert gap.uncovered == ("src/b.py", "src/c.py")


def test_partial_skip_partial_edit_partial_uncovered():
    """A real-world mix: one edited, one explicitly skipped, one missing.
    The missing one trips coverage."""
    plan = {"target_files": ["src/a.py", "src/b.py", "src/c.py"]}
    edit = {
        "edits": [{"file": "src/a.py", "edit_type": "apply_patch", "reason": "fix x"}],
        "skipped_targets": [{"file": "src/b.py", "reason": "regenerated"}],
    }
    gap = check_path_coverage(plan, edit)
    assert isinstance(gap, CoverageGap)
    assert gap.uncovered == ("src/c.py",)


def test_uncovered_targets_are_sorted_deterministically():
    """CoverageGap.uncovered must be sorted so error messages are stable
    across runs / Python set-ordering quirks."""
    plan = {"target_files": ["z.py", "a.py", "m.py"]}
    edit = {"edits": []}
    gap = check_path_coverage(plan, edit)
    assert gap is not None
    assert gap.uncovered == ("a.py", "m.py", "z.py")


# ── path normalisation ──────────────────────────────────────────────────────


def test_leading_dot_slash_normalised():
    """./a.py in the plan and a.py in the edit should match."""
    plan = {"target_files": ["./src/a.py"]}
    edit = {"edits": [{"file": "src/a.py", "edit_type": "apply_patch", "reason": "x"}]}
    assert check_path_coverage(plan, edit) is None


def test_whitespace_normalised():
    """Trailing/leading whitespace in either list shouldn't cause spurious gaps."""
    plan = {"target_files": ["  src/a.py "]}
    edit = {"edits": [{"file": "src/a.py  ", "edit_type": "apply_patch", "reason": "x"}]}
    assert check_path_coverage(plan, edit) is None


def test_case_sensitive_paths_differ():
    """Path comparison stays case-sensitive — A.py and a.py are different
    files on Linux. macOS users will get a real gap; that's correct."""
    plan = {"target_files": ["src/A.py"]}
    edit = {"edits": [{"file": "src/a.py", "edit_type": "apply_patch", "reason": "x"}]}
    gap = check_path_coverage(plan, edit)
    assert gap is not None
    assert gap.uncovered == ("src/A.py",)


# ── defensive paths ─────────────────────────────────────────────────────────


def test_malformed_skipped_targets_ignored_not_crashed():
    """A non-dict entry in skipped_targets is silently dropped, not raised.
    The schema validator already enforces dict shape at the receipt boundary;
    this is just defensive."""
    plan = {"target_files": ["src/a.py"]}
    edit = {
        "edits": [],
        "skipped_targets": ["not a dict"],  # malformed
    }
    gap = check_path_coverage(plan, edit)
    assert gap is not None
    assert gap.uncovered == ("src/a.py",)


def test_error_payload_shape():
    """CoverageGap.as_error_payload returns a stable dict the loop wraps
    as result.validation_error. Test the shape so the workbench renderer
    can rely on the keys."""
    plan = {"target_files": ["a.py", "b.py"]}
    edit = {"edits": []}
    gap = check_path_coverage(plan, edit)
    assert gap is not None
    payload = gap.as_error_payload()
    assert payload["error_code"] == "PHASE_COVERAGE_GAP"
    assert payload["phase"] == "ACT"
    assert "reason" in payload
    assert payload["uncovered_targets"] == ["a.py", "b.py"]


# ── Review fix #4 (2026-05-23) — Windows backslash normalisation ────────────


def test_windows_backslash_paths_match_forward_slash_plan():
    """REGRESSION GUARD for review fix #4.

    Before the fix, _normalise didn't convert ``\\`` → ``/``, so a
    plan that listed ``src/foo.py`` and an EditReceipt that emitted
    ``src\\foo.py`` (from a Windows operator or a repo using
    native backslashes) failed the path-set comparison and tripped
    PHASE_COVERAGE_GAP even though the right file was edited.

    Now the normaliser flips backslashes first, so the two forms
    compare equal.
    """
    plan = {"target_files": ["src/foo.py", "src/bar.py"]}
    edit = {
        "edits": [
            {"file": "src\\foo.py", "edit_type": "apply_patch", "reason": "x"},
            {"file": "src\\bar.py", "edit_type": "apply_patch", "reason": "y"},
        ]
    }
    gap = check_path_coverage(plan, edit)
    assert gap is None, (
        "PHASE_COVERAGE_GAP triggered on Windows-style backslash paths "
        "that match the planned forward-slash paths — _normalise has "
        "regressed."
    )


def test_mixed_slashes_normalise_to_match():
    """Reverse direction: plan uses backslashes, edit uses forward
    slashes. Same equality requirement."""
    plan = {"target_files": ["src\\app\\main.py"]}
    edit = {"edits": [{"file": "src/app/main.py", "edit_type": "apply_patch", "reason": "x"}]}
    assert check_path_coverage(plan, edit) is None


def test_dot_slash_with_backslash_strips_correctly():
    """`.\\foo.py` should normalise to `foo.py`. Tests that the
    backslash → forward-slash replacement runs BEFORE the `./` strip
    loop, so `.\\foo.py` → `./foo.py` → `foo.py`."""
    plan = {"target_files": ["foo.py"]}
    edit = {"edits": [{"file": ".\\foo.py", "edit_type": "apply_patch", "reason": "x"}]}
    assert check_path_coverage(plan, edit) is None
