"""
M71 — Pydantic models for the structured receipts described in spec §17.

The receipt schema is what gates phase advancement: `validators.validate_phase_output()`
parses the agent's phase output into one of these models, and a ValidationError
becomes a `PHASE_OUTPUT_INVALID` 400 back to the agent. Receipt instances are
then persisted on PhaseState.receipts and emitted to audit-gov.

The shapes follow spec §17 verbatim. Optional fields stay optional so prompt
revisions can drop bits without breaking the validator — anything mandatory is
modelled as `Field(...)`.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

from .phase_state import Phase


class ReceiptKind(str, Enum):
    """Discriminator for storage. One per phase + the approval receipt."""

    PLAN = "plan_receipt"
    CONTEXT = "context_receipt"
    EDIT = "edit_receipt"
    VERIFICATION = "verification_receipt"
    REPAIR = "repair_receipt"
    SELF_REVIEW = "self_review_receipt"
    APPROVAL = "approval_receipt"


class _ReceiptBase(BaseModel):
    """Common fields across every receipt. The agent supplies `payload`; the
    validator stamps `created_at` + `kind`.

    `extra="allow"` lets stage-specific overlays add project fields (e.g. a
    capability that wants `mitigation_for_regression_risk` on every PLAN
    receipt). Required-field enforcement for those extras lives in
    StagePolicy.requiredOutputSchema and is checked by `validators.py` on
    top of the Pydantic shape. Sub-models that should stay strict (e.g.
    `EditEntry.edit_type` enum) handle their own validation.
    """

    model_config = ConfigDict(extra="allow")

    kind: ReceiptKind
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


# ─── PLAN ────────────────────────────────────────────────────────────────────


class TestStrategy(BaseModel):
    model_config = ConfigDict(extra="allow")
    commands: list[str] = Field(..., min_length=1)
    reason: str | None = None


class PlanReceipt(_ReceiptBase):
    """Spec §7.1 plan output.

    M72 Slice B — gains optional `config_inspected_files` (max 1 entry).
    Used by multi-module-repo plans that legitimately need to peek at one
    config file (settings.gradle.kts, pom.xml, pyproject.toml) to
    disambiguate the layout before producing target_files. The validator
    enforces the soft cap; broader reads belong in EXPLORE.
    """

    kind: Literal[ReceiptKind.PLAN] = ReceiptKind.PLAN
    target_files: list[str] = Field(..., description="Files the agent expects to touch.")
    expected_edits: list[dict[str, Any]] = Field(default_factory=list)
    symbols_to_inspect: list[str] = Field(default_factory=list)
    test_strategy: TestStrategy
    risk_level: Literal["low", "medium", "high"] = "low"
    external_side_effects_required: bool = False
    assumptions: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    # M72B — optional, capped at max_length=1. Field(default_factory=list)
    # rather than Optional[...] keeps the validator-side check uniform with
    # the StagePolicy.requiredOutputSchema (which uses maxItems: 1).
    config_inspected_files: list[str] = Field(default_factory=list, max_length=1)


# ─── CONTEXT (EXPLORE phase) ─────────────────────────────────────────────────


class ContextItem(BaseModel):
    model_config = ConfigDict(extra="allow")
    type: Literal["repo_map", "symbol", "ast_slice", "dependency_slice", "file"]
    target: str
    reason: str
    token_estimate: int = 0


class ContextReceipt(_ReceiptBase):
    """Spec §7.2 explore output."""

    kind: Literal[ReceiptKind.CONTEXT] = ReceiptKind.CONTEXT
    context_used: list[ContextItem] = Field(default_factory=list)
    implementation_findings: list[str] = Field(default_factory=list)
    updated_target_files: list[str] = Field(default_factory=list)
    updated_test_strategy: dict[str, Any] | None = None


# ─── EDIT (ACT phase) ────────────────────────────────────────────────────────


class EditEntry(BaseModel):
    model_config = ConfigDict(extra="allow")
    file: str
    edit_type: Literal["apply_patch", "replace_text", "replace_range", "create_file", "write_file"]
    reason: str
    anchor_hash: str | None = None
    before_summary: str | None = None
    after_summary: str | None = None


class SkippedTarget(BaseModel):
    """M74 Phase 1B — agent's explicit declaration that a PlanReceipt
    target_file was deliberately not edited. Used by the path-coverage
    check in loop.py to allow legitimate scope reductions without
    refusing the ACT→VERIFY advance.

    Example reasons: "test file regenerated by build, no manual edit",
    "no longer needed after refactor consolidated logic into base.py",
    "deferred to follow-up issue per discovered scope expansion".
    """
    model_config = ConfigDict(extra="allow")
    file: str
    reason: str


class EditReceipt(_ReceiptBase):
    """Spec §7.3 act output."""

    kind: Literal[ReceiptKind.EDIT] = ReceiptKind.EDIT
    edits: list[EditEntry] = Field(..., min_length=1)
    # M74 Phase 1B — when the agent legitimately chose not to edit a
    # PlanReceipt.target_files entry, declare it here with a reason.
    # The path-coverage check (loop.py, ACT→VERIFY advance) refuses to
    # advance if any plan target is neither in edits[].file nor in
    # skipped_targets[].file. Empty list is fine when the EditReceipt
    # fully covers the plan.
    skipped_targets: list[SkippedTarget] = Field(default_factory=list)


# ─── VERIFICATION (VERIFY phase) ─────────────────────────────────────────────


class CommandResult(BaseModel):
    model_config = ConfigDict(extra="allow")
    command: str
    exit_code: int = 0
    duration_ms: int = 0
    stdout_summary: str = ""
    stderr_summary: str = ""


class CoverageMap(BaseModel):
    model_config = ConfigDict(extra="allow")
    targeted_tests: bool = False
    full_tests: bool = False
    lint: bool = False
    typecheck: bool = False
    compile: bool = False


class VerificationResultPayload(BaseModel):
    model_config = ConfigDict(extra="allow")
    status: Literal["passed", "failed", "unavailable"]
    commands_run: list[CommandResult] = Field(default_factory=list)
    coverage: CoverageMap = Field(default_factory=CoverageMap)
    evidence_files: list[str] = Field(default_factory=list)
    # Required when status == "unavailable" — the spec wants an explicit reason
    # so reviewers can decide whether the gap is acceptable.
    reason: str | None = None
    fallback_checks: list[str] = Field(default_factory=list)

    # M74 Phase 1C — close the fake-pass loophole. Under the old shape an
    # agent could submit `{status: "passed", commands_run: []}` and have
    # the phase machine happily advance to SELF_REVIEW with zero evidence
    # that any verifier actually ran. The schema was structurally valid
    # because commands_run had a default. Now it's structurally required
    # for passed/failed — only "unavailable" can have an empty list (and
    # that path requires `reason` to be set, enforced just below).
    @model_validator(mode="after")
    def _passed_or_failed_requires_commands(self) -> "VerificationResultPayload":
        if self.status in ("passed", "failed") and not self.commands_run:
            raise ValueError(
                f"VerificationResultPayload: status={self.status!r} requires "
                "commands_run to be non-empty — at least one command must have "
                "been executed to substantiate the verdict. If no verifier "
                "could be run, set status='unavailable' with a `reason`."
            )
        # Fix (review issue #5, 2026-05-23) — close the
        # "confidently-wrong" loophole. The Phase 1C validator above
        # only checked that commands_run was non-empty; it didn't
        # check the exit codes. A model could submit
        # status='passed' alongside a CommandResult with exit_code=1
        # and the receipt would validate, letting it bypass the
        # verification gate and advance to SELF_REVIEW with failing
        # tests. Now: if status is 'passed', every command in
        # commands_run must have exit_code == 0. If any failed, the
        # correct status is 'failed' (which advances to REPAIR
        # under the phase machine's verify→repair edge).
        if self.status == "passed":
            failed = [c.command for c in self.commands_run if c.exit_code != 0]
            if failed:
                raise ValueError(
                    "VerificationResultPayload: status cannot be 'passed' when "
                    f"underlying verifiers returned non-zero exit codes for: "
                    f"{failed!r}. Either set status='failed' (advances to REPAIR), "
                    "or fix the failing commands and re-run."
                )
        if self.status == "unavailable" and not (self.reason and self.reason.strip()):
            raise ValueError(
                "VerificationResultPayload: status='unavailable' requires a "
                "non-empty `reason` so reviewers can decide whether the gap is "
                "acceptable. Examples: 'no test framework configured', "
                "'verifier-registry returned no candidates for changed paths'."
            )
        return self


class VerificationReceipt(_ReceiptBase):
    """Spec §7.4 verify output. Mandatory for stage approval."""

    kind: Literal[ReceiptKind.VERIFICATION] = ReceiptKind.VERIFICATION
    verification_result: VerificationResultPayload


# ─── REPAIR ──────────────────────────────────────────────────────────────────


class RepairReceipt(_ReceiptBase):
    """Spec §7.5 repair output."""

    kind: Literal[ReceiptKind.REPAIR] = ReceiptKind.REPAIR
    retry_number: int = Field(..., ge=1)
    failure_summary: str
    repair_hypothesis: str
    files_to_reinspect: list[str] = Field(default_factory=list)
    edits: list[EditEntry] = Field(default_factory=list)
    expected_fix: str | None = None


# ─── SELF_REVIEW ─────────────────────────────────────────────────────────────


class AcceptanceCheck(BaseModel):
    model_config = ConfigDict(extra="allow")
    criterion: str
    status: Literal["met", "not_met", "uncertain"]
    evidence: str | None = None


class RiskSummary(BaseModel):
    model_config = ConfigDict(extra="allow")
    risk_level: Literal["low", "medium", "high"] = "low"
    risks: list[str] = Field(default_factory=list)
    rollback_notes: str | None = None


class DiffSummary(BaseModel):
    model_config = ConfigDict(extra="allow")
    files_changed: list[str] = Field(default_factory=list)
    lines_added: int = 0
    lines_deleted: int = 0
    notable_changes: list[str] = Field(default_factory=list)


class SelfReviewReceipt(_ReceiptBase):
    """Spec §7.6 self-review output. Gates the approval gate."""

    kind: Literal[ReceiptKind.SELF_REVIEW] = ReceiptKind.SELF_REVIEW
    summary: str = ""
    acceptance_criteria_check: list[AcceptanceCheck] = Field(default_factory=list)
    risk_summary: RiskSummary = Field(default_factory=RiskSummary)
    diff_summary: DiffSummary = Field(default_factory=DiffSummary)
    verification_summary: str = ""
    recommended_for_approval: bool = False

    # M73-followup #4 — confidently-wrong agents will mark their own work
    # `recommended_for_approval=True` even when their own acceptance-criteria
    # checks contradict that. The human-approval gate downstream is meant to
    # catch this, but the model's recommendation is what the gate's pre-fill
    # state and the workbench's "ready to approve" banner key off — so a
    # falsely-true recommendation poisons the operator's first-impression UX.
    #
    # Refuse the receipt at the model boundary:
    #   • If ANY criterion has status="not_met" → recommended_for_approval
    #     MUST be False. Hard refuse.
    #   • If >=2 criteria have status="uncertain" → ditto. Two unknowns is
    #     enough doubt that the agent shouldn't be self-certifying.
    #
    # The agent can still complete SELF_REVIEW phase — it just has to flip
    # the recommendation to False (and the workbench will render the partial
    # evidence accordingly). This is structural, not advisory.
    @model_validator(mode="after")
    def _refuse_inconsistent_recommendation(self) -> "SelfReviewReceipt":
        if not self.recommended_for_approval:
            return self
        not_met = [c.criterion for c in self.acceptance_criteria_check if c.status == "not_met"]
        if not_met:
            raise ValueError(
                "SelfReviewReceipt: recommended_for_approval=True is forbidden "
                f"when any acceptance criterion is not_met (failing: {not_met!r}). "
                "Set recommended_for_approval=False and let the human gate decide."
            )
        uncertain = [c.criterion for c in self.acceptance_criteria_check if c.status == "uncertain"]
        if len(uncertain) >= 2:
            raise ValueError(
                "SelfReviewReceipt: recommended_for_approval=True is forbidden "
                f"when 2 or more acceptance criteria are uncertain (uncertain: {uncertain!r}). "
                "Either provide evidence or set recommended_for_approval=False."
            )
        return self


# ─── APPROVAL (workgraph-api stamps these, not the agent) ────────────────────


class ApprovalReceipt(_ReceiptBase):
    """Spec §17.4. Persisted when a human approves a stage. Not produced by
    the agent — workgraph-api builds this from the approval form."""

    kind: Literal[ReceiptKind.APPROVAL] = ReceiptKind.APPROVAL
    decision: Literal["approved", "changes_requested", "rejected"]
    approver: str
    comments: str | None = None
    approved_actions: list[str] = Field(default_factory=list)
    blocked_actions: list[str] = Field(default_factory=list)


# ─── Phase → receipt lookup ──────────────────────────────────────────────────


_PHASE_TO_MODEL: dict[Phase, type[_ReceiptBase]] = {
    Phase.PLAN: PlanReceipt,
    Phase.EXPLORE: ContextReceipt,
    Phase.ACT: EditReceipt,
    Phase.VERIFY: VerificationReceipt,
    Phase.REPAIR: RepairReceipt,
    Phase.SELF_REVIEW: SelfReviewReceipt,
    # FINALIZE doesn't carry a receipt of its own — finalize-time artifacts
    # (branch SHA, commit SHA, PR URL) are returned in the response body but
    # don't flow through this validator pipeline.
}


def receipt_for_phase(phase: Phase) -> type[_ReceiptBase] | None:
    """Return the Pydantic model the validator should use for `phase`, or
    None for phases that don't emit a structured receipt (FINALIZE)."""
    return _PHASE_TO_MODEL.get(phase)
