/**
 * M42.2 — Handlebars template engine + shared helpers.
 *
 * Templates live in src/templates/<stack>/*.hbs and are read fresh per
 * generation (no in-memory cache — generation is bursty and the YAML
 * specs are small so the cost is negligible, but we get hot-reload of
 * template edits for free during dev).
 *
 * Helpers register the cross-stack utilities templates rely on:
 *   {{eq a b}}                  equality test
 *   {{any list}}                 → list.length > 0
 *   {{capitalize "foo"}}         → "Foo"
 *   {{snake "fooBar"}}           → "foo_bar"
 *   {{kebab "fooBar"}}           → "foo-bar"
 *   {{constant "fooBar"}}        → "FOO_BAR"
 *   {{javaTypeOf field}}         pull javaType off the field
 *   {{pythonTypeOf field}}
 *   {{tsTypeOf field}}
 *   {{json value}}               JSON-encode (handy for OpenAPI emit)
 *   {{header lines lang}}        emit a generated-by header
 *   {{protectedRegion id lang}}{{contents}}{{/protectedRegion}}
 *   {{editableRegion  id lang}}{{placeholder}}{{/editableRegion}}
 */
import Handlebars from 'handlebars'
import { fence, headerComment } from '../regions/markers.js'
import type { RegionMarkerLanguage } from '../regions/ontology.js'

let registered = false

function registerHelpers(): void {
  if (registered) return
  registered = true

  Handlebars.registerHelper('eq', (a: unknown, b: unknown) => a === b)
  Handlebars.registerHelper('any', (list: unknown[] | undefined) => Array.isArray(list) && list.length > 0)
  Handlebars.registerHelper('capitalize', (s: string) =>
    typeof s === 'string' && s.length > 0 ? s[0].toUpperCase() + s.slice(1) : s,
  )
  Handlebars.registerHelper('uncapitalize', (s: string) =>
    typeof s === 'string' && s.length > 0 ? s[0].toLowerCase() + s.slice(1) : s,
  )
  Handlebars.registerHelper('snake', (s: string) =>
    typeof s === 'string' ? s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase() : s,
  )
  Handlebars.registerHelper('kebab', (s: string) =>
    typeof s === 'string' ? s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase() : s,
  )
  Handlebars.registerHelper('constant', (s: string) =>
    typeof s === 'string' ? s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase() : s,
  )
  Handlebars.registerHelper('lowercaseMethod', (m: string) => typeof m === 'string' ? m.toLowerCase() : m)
  Handlebars.registerHelper('zodFor', (jsonType: string): string => {
    switch (jsonType) {
      case 'string': return 'z.string()'
      case 'integer': return 'z.number().int()'
      case 'number': return 'z.number()'
      case 'boolean': return 'z.boolean()'
      case 'array': return 'z.array(z.unknown())'
      default: return 'z.unknown()'
    }
  })
  Handlebars.registerHelper('json', (v: unknown) => new Handlebars.SafeString(JSON.stringify(v, null, 2)))
  Handlebars.registerHelper('joinPath', (...args: unknown[]) => {
    const parts = args.slice(0, -1) as string[]
    return parts.filter(Boolean).map(p => p.replace(/^\/+|\/+$/g, '')).filter(Boolean).join('/')
  })
  Handlebars.registerHelper('packageToPath', (pkg: string) =>
    typeof pkg === 'string' ? pkg.replace(/\./g, '/') : pkg,
  )

  // Generated-by header. Stamps spec/IR/template versions so every file
  // can be traced back to the generation run.
  Handlebars.registerHelper('header', function (this: { meta?: { specHash?: string; irHash?: string; templateVersion?: string; generatorVersion?: string } }, lang: RegionMarkerLanguage) {
    const meta = this?.meta ?? {}
    return new Handlebars.SafeString(
      headerComment(lang, [
        'Generated by Singularity Code Foundry',
        `Generator: ${meta.generatorVersion ?? '?'}`,
        `Template:  ${meta.templateVersion ?? '?'}`,
        `Spec hash: ${meta.specHash ?? '?'}`,
        `IR hash:   ${meta.irHash ?? '?'}`,
        'Manual edits inside <generated:protected> regions are not allowed.',
      ]),
    )
  })

  // Block helpers wrap their contents in a typed region marker.
  Handlebars.registerHelper('protectedRegion', function (this: unknown, regionId: string, lang: RegionMarkerLanguage, options: Handlebars.HelperOptions) {
    const body = options.fn(this)
    return new Handlebars.SafeString(fence({ marker: 'protected', regionId, language: lang, body: body.trimEnd() }))
  })
  Handlebars.registerHelper('editableRegion', function (this: unknown, regionId: string, lang: RegionMarkerLanguage, options: Handlebars.HelperOptions) {
    const body = options.fn(this)
    return new Handlebars.SafeString(fence({ marker: 'editable', regionId, language: lang, body: body.trimEnd() }))
  })
}

export function compile(source: string): HandlebarsTemplateDelegate {
  registerHelpers()
  // Non-strict so templates can reference optional spec fields
  // (e.g. {{metadata.description}}) without throwing when absent.
  // The verifier (M42.3) catches typos by grepping the generated output
  // for stray {{ moustaches.
  return Handlebars.compile(source, { noEscape: true, strict: false })
}

export function render(source: string, vars: object): string {
  return compile(source)(vars)
}
