"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BadgeDollarSign, CalendarRange, Coins, Save, TimerReset } from "lucide-react";
import { workgraphFetch, WorkgraphError } from "@/lib/workgraph";
import { SynthesisShell } from "@/components/synthesis/SynthesisShell";
import { NoProjectSelected, ProjectPicker, useSelectedProjectId } from "@/components/synthesis/ProjectPicker";
import { useProjectEconomics } from "@/components/synthesis/hooks/useSynthesis";
import { EmptyState, MonoMeta, StageHeader, SynButton, SynCard, SynChip, SynError, SynSkeleton } from "@/components/synthesis/ui/kit";

const control = "w-full rounded-md border border-outline-variant bg-surface px-3 py-2 text-sm text-on-surface outline-none focus:border-secondary";

export function EconomicsWorkspaceScreen() {
  const pathname = usePathname() ?? "/synthesis/economics";
  const projectId = useSelectedProjectId();
  return <SynthesisShell title="Economics & Timeline" headerActions={<ProjectPicker pathname={pathname} />}>{projectId ? <Economics projectId={projectId} /> : <NoProjectSelected surface="Economics & Timeline" />}</SynthesisShell>;
}

function Economics({ projectId }: { projectId: string }) {
  const query = useProjectEconomics(projectId);
  const [form, setForm] = useState({ currency: "USD", budgetLow: "", budgetHigh: "", tokenLimit: "", warningPercent: "80", hardCapPercent: "120" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { const envelope = query.data?.envelope; if (envelope) setForm({ currency: envelope.currency, budgetLow: String(envelope.budgetLow ?? ""), budgetHigh: String(envelope.budgetHigh ?? ""), tokenLimit: String(envelope.tokenLimit ?? ""), warningPercent: String(envelope.warningPercent), hardCapPercent: String(envelope.hardCapPercent) }); }, [query.data?.envelope]);
  const rows = useMemo(() => (query.data?.plans ?? []).flatMap(plan => plan.rows.map(row => ({ plan, row }))).sort((left, right) => String(left.row.projectedStartAt ?? "").localeCompare(String(right.row.projectedStartAt ?? ""))), [query.data?.plans]);
  const save = async () => { setBusy(true); setError(null); try { await workgraphFetch(`/studio/projects/${projectId}/budget-envelope`, { method: "PUT", body: JSON.stringify({ currency: form.currency, budgetLow: nullableNumber(form.budgetLow), budgetHigh: nullableNumber(form.budgetHigh), tokenLimit: nullableNumber(form.tokenLimit), warningPercent: Number(form.warningPercent), hardCapPercent: Number(form.hardCapPercent) }) }); await query.mutate(); } catch (cause) { setError(cause instanceof WorkgraphError ? cause.message : "Could not update the budget envelope."); } finally { setBusy(false); } };
  if (query.isLoading) return <SynSkeleton rows={6} />;
  if (query.error || !query.data) return <SynError message={(query.error as Error)?.message ?? "Economics data is unavailable."} />;
  const data = query.data;
  return <div className="space-y-7"><StageHeader eyebrow="Plan · Spend · Learn" title="Economics and delivery timeline" description="Track planned delivery cost against real model consumption, with one critical-path schedule derived from the generation plan." icon={BadgeDollarSign} />{error ? <SynError message={error} /> : null}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={BadgeDollarSign} label="Plan estimate" value={`$${data.rollup.estimatedPlanCostHigh.toLocaleString()}`} detail="High estimate across plan rows" /><Metric icon={Coins} label="LLM cost" value={`$${data.rollup.ledgerCostUsd.toFixed(2)}`} detail={`${data.rollup.costPercent ?? 0}% of envelope`} /><Metric icon={TimerReset} label="Tokens used" value={data.rollup.ledgerTokens.toLocaleString()} detail={`${data.rollup.tokenPercent ?? 0}% of token limit`} /><Metric icon={CalendarRange} label="Scheduled work" value={String(rows.length)} detail={`${rows.filter(item => item.row.criticalPath).length} critical-path item(s)`} /></div>
    <SynCard className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-black text-on-surface">Initiative budget envelope</h2><p className="mt-1 text-sm text-on-surface-variant">Warnings appear before the limit; plans beyond 100% need a DRI waiver and the hard cap remains non-bypassable.</p></div><SynButton icon={Save} disabled={busy} onClick={() => void save()}>{busy ? "Saving…" : "Save envelope"}</SynButton></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Field label="Currency"><input className={control} maxLength={3} value={form.currency} onChange={event => setForm(current => ({ ...current, currency: event.target.value.toUpperCase() }))} /></Field><Field label="Budget low"><input className={control} type="number" min="0" value={form.budgetLow} onChange={event => setForm(current => ({ ...current, budgetLow: event.target.value }))} /></Field><Field label="Budget high"><input className={control} type="number" min="0" value={form.budgetHigh} onChange={event => setForm(current => ({ ...current, budgetHigh: event.target.value }))} /></Field><Field label="Token limit"><input className={control} type="number" min="1" value={form.tokenLimit} onChange={event => setForm(current => ({ ...current, tokenLimit: event.target.value }))} /></Field><Field label="Warn at %"><input className={control} type="number" min="1" max="100" value={form.warningPercent} onChange={event => setForm(current => ({ ...current, warningPercent: event.target.value }))} /></Field><Field label="Hard cap %"><input className={control} type="number" min="100" max="200" value={form.hardCapPercent} onChange={event => setForm(current => ({ ...current, hardCapPercent: event.target.value }))} /></Field></div></SynCard>
    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="font-black text-on-surface">Critical-path timeline</h2><p className="text-xs text-on-surface-variant">Dates are deterministic weekday schedules created during plan validation.</p></div><Link className="text-xs font-bold text-secondary" href={`/synthesis/generate?projectId=${encodeURIComponent(projectId)}`}>Open generation</Link></div>{!rows.length ? <EmptyState icon={CalendarRange} title="No validated schedule" description="Validate a generation plan to calculate projected dates and the critical path." /> : <div className="overflow-hidden rounded-md border border-outline-variant bg-surface"><div className="grid grid-cols-[minmax(180px,1fr)_120px_120px_100px_90px] gap-3 border-b border-outline-variant bg-surface-container px-4 py-2 text-[10px] font-black uppercase text-on-surface-variant"><span>WorkItem plan row</span><span>Start</span><span>Finish</span><span>Hours</span><span>State</span></div>{rows.map(({ plan, row }) => <div key={row.id} className="grid grid-cols-[minmax(180px,1fr)_120px_120px_100px_90px] gap-3 border-b border-outline-variant px-4 py-3 text-xs last:border-b-0"><span className="min-w-0"><strong className="block truncate text-on-surface">{row.title}</strong><span className="text-on-surface-variant">{plan.status}{row.criticalPath ? " · critical path" : ""}</span></span><span>{formatDate(row.projectedStartAt)}</span><span>{formatDate(row.projectedFinishAt)}</span><span>{row.estimatedHours ?? "–"}</span><SynChip tone={row.state === "APPLIED" ? "success" : row.state === "FAILED" ? "error" : "neutral"}>{row.state}</SynChip></div>)}</div>}</section>
    <section><h2 className="mb-3 font-black text-on-surface">Model usage ledger</h2>{!data.ledger.length ? <EmptyState icon={Coins} title="No model usage recorded" description="Workflow node usage attached to this initiative will appear here with trace links." /> : <div className="space-y-2">{data.ledger.slice(0, 30).map(entry => <div key={entry.id} className="flex flex-wrap items-center gap-3 rounded-md border border-outline-variant bg-surface px-4 py-3 text-xs"><strong>{entry.stage ?? "Workflow"}</strong><span>{entry.provider ?? "provider"} / {entry.model ?? "model"}</span><span className="ml-auto">{entry.totalTokens.toLocaleString()} tokens · ${(entry.estimatedCostUsd ?? 0).toFixed(4)}</span>{entry.traceId ? <Link className="font-bold text-secondary" href={`/audit/trace/${encodeURIComponent(entry.traceId)}`}>Trace</Link> : null}</div>)}</div>}</section>
  </div>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof BadgeDollarSign; label: string; value: string; detail: string }) { return <div className="rounded-md border border-outline-variant bg-surface p-4"><div className="flex items-center gap-2 text-on-surface-variant"><Icon size={15} /><MonoMeta>{label}</MonoMeta></div><div className="mt-3 text-2xl font-black text-on-surface">{value}</div><p className="mt-1 text-xs text-on-surface-variant">{detail}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-xs font-bold text-on-surface-variant">{label}{children}</label>; }
function nullableNumber(value: string) { if (!value.trim()) return null; const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleDateString() : "–"; }
