/**
 * Contract: what the LLM gateway emits vs what llmCallPayload accepts.
 *
 * This is the highest-value test in the gateway-emitter change, because the
 * failure it guards is completely silent. cost-worker.ts does:
 *
 *     const parsed = llmCallPayload.safeParse(payloadIn);
 *     if (!parsed.success) return;
 *
 * — so a payload the schema rejects produces NO llm_calls row and NO error.
 * And z.object() strips unknown keys rather than complaining, so a field the
 * schema does not declare vanishes just as quietly. Either way the symptom is
 * identical to the bug this whole change exists to fix: an empty table.
 *
 * The fixture is generated by the REAL Python emitter (see
 * test/fixtures/regenerate-gateway-fixture.py). Python and TypeScript cannot
 * import each other, so the checked-in JSON is the seam, and both sides assert
 * against it.
 */
import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { llmCallPayload } from "../src/types";

const fixture = JSON.parse(
  fs.readFileSync(path.join(process.cwd(), "test/fixtures/gateway-llm-call-payload.json"), "utf8"),
) as Record<string, { payload: Record<string, unknown> } & Record<string, unknown>>;

const CHAT = fixture.chat_completions;
const EMBED = fixture.embeddings;

/**
 * Fields the gateway sends that llm_calls has no column for, so llmCallPayload
 * deliberately does not declare them. They survive on audit_events.payload
 * (and cost-worker's savings denormaliser reads run_id off the RAW payload),
 * they just do not reach the cost row. Anything ELSE going missing is a bug.
 */
const INTENTIONALLY_NOT_ON_THE_COST_ROW = new Set(["run_id"]);

describe("gateway llm.call.completed payload / llmCallPayload contract", () => {
  it("the emitter's chat payload parses", () => {
    const parsed = llmCallPayload.safeParse(CHAT.payload);
    // Print the actual zod issue rather than a bare `false` — a failure here
    // means production would be recording nothing, and the field name is the
    // whole diagnosis.
    expect(parsed.success ? null : parsed.error.issues).toBe(null);
  });

  it("the emitter's embeddings payload parses", () => {
    const parsed = llmCallPayload.safeParse(EMBED.payload);
    expect(parsed.success ? null : parsed.error.issues).toBe(null);
  });

  it("keeps every field the emitter sends — nothing silently stripped", () => {
    for (const [name, sample] of [["chat", CHAT], ["embeddings", EMBED]] as const) {
      const parsed = llmCallPayload.parse(sample.payload);
      for (const key of Object.keys(sample.payload)) {
        if (INTENTIONALLY_NOT_ON_THE_COST_ROW.has(key)) continue;
        expect(parsed, `${name}.${key} was stripped by llmCallPayload`).toHaveProperty(key);
      }
    }
  });

  it("carries the identity, provenance and fingerprint fields m75 added", () => {
    const parsed = llmCallPayload.parse(CHAT.payload);
    // These are the columns m75 added and the reason the emitter exists. If any
    // of them stops arriving, llm_calls is back to answering "what did it cost"
    // without being able to say for whom, for what, or against which price.
    expect(parsed.actor_id).toBe("user-1042");
    expect(parsed.model_alias).toBe("balanced");
    expect(parsed.task_tag).toBe("agent_turn");
    expect(parsed.stage).toBe("develop");
    expect(parsed.purpose).toBe("code_edit");
    expect(parsed.endpoint).toBe("chat_completions");
    expect(parsed.routing_source).toBe("caller_pin");
    expect(parsed.gateway_call_id).toBe("6f1a9c4e-3b2d-4f8a-9c1e-7d5b2a8f0c31");
    expect(parsed.price_source).toBe("gateway_catalog");
    expect(parsed.cost_usd).toBe(0.017388);
    expect(parsed.prompt_sha256).toHaveLength(64);
    expect(parsed.response_sha256).toHaveLength(64);
    expect(parsed.prompt_chars).toBe(27);
    expect(parsed.response_chars).toBe(19);
  });

  it("carries NO prompt or response text — fingerprints and counts only", () => {
    // The privacy invariant, checked against the serialized payload rather than
    // a field list so a future field cannot smuggle text past it. The fixture's
    // plaintexts are known, so their absence is directly assertable.
    for (const sample of [CHAT, EMBED]) {
      const serialized = JSON.stringify(sample);
      for (const secret of [
        "SYSTEM PROMPT AND USER TURN",
        "MODEL RESPONSE TEXT",
        "DOCUMENT CHUNK TEXT",
      ]) {
        expect(serialized).not.toContain(secret);
      }
      for (const banned of ["prompt", "response", "content", "messages", "input", "text"]) {
        expect(Object.keys(sample.payload)).not.toContain(banned);
        expect(Object.keys(sample.payload)).not.toContain(`${banned}_text`);
      }
    }
  });

  it("still accepts a legacy emitter that sends only the original fields", () => {
    // mcp-server's pre-M71 loop shape. Every M75 field is optional precisely so
    // adding the gateway emitter cannot retroactively break an older producer.
    const legacy = {
      provider: "openai",
      model: "gpt-4o-mini",
      input_tokens: 100,
      output_tokens: 20,
      latency_ms: 900,
      finish_reason: "stop",
    };
    expect(llmCallPayload.safeParse(legacy).success).toBe(true);
  });

  it("degrades one malformed field to undefined instead of dropping the whole row", () => {
    // The trap this schema is built around: a strict field turns a cosmetic
    // problem into total data loss, because safeParse failure means no row at
    // all. Losing gateway_call_id is an inconvenience; losing the spend is not.
    const parsed = llmCallPayload.safeParse({
      ...CHAT.payload,
      gateway_call_id: "not-a-uuid",
      prompt_chars: "many",
      cost_usd: -1,
    });
    expect(parsed.success).toBe(true);
    if (parsed.success) {
      expect(parsed.data.gateway_call_id).toBeUndefined();
      expect(parsed.data.prompt_chars).toBeUndefined();
      expect(parsed.data.cost_usd).toBeUndefined();
      // The load-bearing part: the spend still lands.
      expect(parsed.data.input_tokens).toBe(4211);
      expect(parsed.data.output_tokens).toBe(317);
    }
  });

  it("still rejects a payload with no usable cost data at all", () => {
    // Leniency has a floor. Without provider/model/tokens there is nothing to
    // denormalise and a row would be worse than no row.
    expect(llmCallPayload.safeParse({ provider: "openai" }).success).toBe(false);
    expect(llmCallPayload.safeParse({}).success).toBe(false);
  });

  it("is emitted under the kind and source the cost worker keys on", () => {
    // ingestOne only calls denormaliseLlmCall when kind === "llm.call.completed".
    // A renamed kind is another silent no-row failure.
    expect(CHAT.kind).toBe("llm.call.completed");
    expect(CHAT.source_service).toBe("llm-gateway");
    // subject_id === gateway_call_id is what lets the audit_events row and the
    // llm_calls row be joined exactly rather than by timestamp proximity.
    expect(CHAT.subject_id).toBe((CHAT.payload as Record<string, unknown>).gateway_call_id);
  });
});
