#!/usr/bin/env python3
"""
Regenerate gateway-llm-call-payload.json from the REAL gateway emitter.

    cd context-fabric && PYTHONPATH="services:shared" \
        python3 ../audit-governance-service/test/fixtures/regenerate-gateway-fixture.py

The fixture is the contract between two languages that cannot import each
other. It matters because the failure it guards is SILENT: cost-worker.ts
safeParses the payload against llmCallPayload and returns quietly when the
parse fails, so a field the schema does not declare is stripped without a word
and a field of the wrong type drops the entire cost row. Nothing errors,
nothing logs, the row just never appears.

So both sides assert against this file:
  - context-fabric/tests/test_gateway_audit_emit.py — the emitter still
    produces exactly this
  - audit-governance-service/test/gateway-llm-call-payload.contract.test.ts —
    llmCallPayload still accepts it, field for field, without stripping

Change the emitter without changing the schema (or vice versa) and a test
fails, instead of production quietly recording nothing.
"""
from __future__ import annotations

import json
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

from llm_gateway_service.app import audit_emit as a  # noqa: E402

CHAT = dict(
    gateway_call_id="6f1a9c4e-3b2d-4f8a-9c1e-7d5b2a8f0c31",
    endpoint="chat_completions",
    provider="anthropic",
    model="claude-sonnet-4-5-20250929",
    model_alias="balanced",
    identity={"task_tag": "agent_turn", "stage": "develop", "purpose": "code_edit"},
    input_tokens=4211,
    output_tokens=317,
    latency_ms=8420,
    finish_reason="stop",
    routing_source="caller_pin",
    estimated_cost=0.017388,
    trace_id="trace-7f3c",
    capability_id="cap-sdlc-dev",
    tenant_id="tenant-acme",
    actor_id="user-1042",
    run_id="run-88",
    prompt_sha256=a.sha256_text("SYSTEM PROMPT AND USER TURN"),
    prompt_chars=27,
    response_sha256=a.sha256_text("MODEL RESPONSE TEXT"),
    response_chars=19,
)

EMB = dict(
    gateway_call_id="b2c4d6e8-1a3f-4b5c-8d9e-0f1a2b3c4d5e",
    endpoint="embeddings",
    provider="openai",
    model="text-embedding-3-small",
    model_alias="embed-small",
    identity={"task_tag": "embedding", "stage": None, "purpose": None},
    input_tokens=912,
    output_tokens=0,
    latency_ms=140,
    routing_source="default",
    estimated_cost=0.0000182,
    trace_id="trace-91ab",
    capability_id="cap-world-model",
    tenant_id="tenant-acme",
    # The m75 convention for a call with no human behind it.
    actor_id="system:context-fabric",
    prompt_sha256=a.sha256_text("DOCUMENT CHUNK TEXT"),
    prompt_chars=19,
)

README = (
    "GENERATED by context-fabric/services/llm_gateway_service/app/audit_emit.py "
    "build_event(). Regenerate with: python3 "
    "audit-governance-service/test/fixtures/regenerate-gateway-fixture.py. "
    "Asserted from BOTH sides: context-fabric/tests/test_gateway_audit_emit.py "
    "checks the emitter still produces this; "
    "audit-governance-service/test/gateway-llm-call-payload.contract.test.ts "
    "checks llmCallPayload still accepts it without stripping. A drift on "
    "either side fails a test instead of silently emitting nothing."
)


def main() -> None:
    out = {
        "README": README,
        "chat_completions": a.build_event(**CHAT),
        "embeddings": a.build_event(**EMB),
    }
    path = Path(__file__).resolve().parent / "gateway-llm-call-payload.json"
    path.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
