export type GuideNode = {
  key: string;
  label: string;
  category: "flow" | "human" | "agent" | "data" | "integration" | "governance" | "timing";
  summary: string;
  whenToUse: string;
  execution: string;
  configuration: string[];
  output: string;
  caution?: string;
  example?: string;
};

export const GUIDE_NODES: Record<string, GuideNode> = {
  START: { key: "START", label: "Start", category: "flow", summary: "The entry point for a workflow run.", whenToUse: "Every executable workflow needs one clear start node.", execution: "Server-side; completes immediately and passes the initial context downstream.", configuration: ["Label the business event or starting condition.", "Use incoming WorkItem fields and documents as the initial context."], output: "Initial workflow context and the first active edge.", caution: "Do not add multiple entry points unless the workflow trigger contract explicitly supports them." },
  END: { key: "END", label: "End", category: "flow", summary: "Marks successful completion of a workflow path.", whenToUse: "Use one at the end of each terminal path so the run has an explicit completion state.", execution: "Server-side; completes immediately.", configuration: ["Add a label that says what the path delivered.", "Persist important results before End with Create Artifact or Data Sink."], output: "A completed workflow path and final context.", caution: "End does not automatically publish documents, commits, or external events." },
  HUMAN_TASK: { key: "HUMAN_TASK", label: "Human Task", category: "human", summary: "Creates an assigned task for a person to provide input or make a decision.", whenToUse: "Use when a person must supply missing information or perform a controlled action.", execution: "Server-side; the node remains ACTIVE until the task is completed or expires.", configuration: ["Assignee or team.", "Question/instructions and required fields.", "Due date, escalation, and send-back behavior."], output: "Human response and task decision in workflow context.", caution: "A run waiting for human input is ACTIVE, not failed. Show the task owner and next action in the run cockpit." },
  APPROVAL: { key: "APPROVAL", label: "Approval", category: "human", summary: "Pauses until an authorized approver accepts or rejects a change.", whenToUse: "Use before high-impact actions such as release, external communication, or production changes.", execution: "Server-side; waits for an approval decision and records an audit receipt.", configuration: ["Approver or approver group.", "Minimum approvals.", "Due date and escalation target.", "Reject/send-back route."], output: "Approved or rejected decision with approver identity and timestamp.", caution: "Approval is not the same as a governance analysis; pair it with a Governance Gate when evidence must be evaluated." },
  AGENT_TASK: { key: "AGENT_TASK", label: "Agent Task", category: "agent", summary: "Runs a governed agent using its prompt profile, skills, tools, and runtime policy.", whenToUse: "Use for multi-step reasoning or tool use grounded in a capability and agent profile.", execution: "Normally Context Fabric → Runtime Bridge → MCP/LLM runtime; direct routes are explicit node configuration.", configuration: ["Agent/profile binding.", "Prompt or URL-backed skill source.", "Input variable mappings.", "LLM route: Context Fabric governed, Context Fabric direct, or WorkGraph direct.", "Co-work/human review behavior and output schema."], output: "Agent response, structured fields, artifacts, tool receipts, and trace correlation.", caution: "Never put an API key in node JSON. Store only the environment-variable name and keep the actual secret in the executing service." , example: "Use a verifier agent with a read-only design URL and an output schema containing verdict, confidence, and findings." },
  DIRECT_LLM_TASK: { key: "DIRECT_LLM_TASK", label: "Direct LLM Task", category: "agent", summary: "Calls a configured LLM provider with a prompt and structured output without MCP tool execution.", whenToUse: "Use for isolated classification, extraction, drafting, or verification when tools are unnecessary.", execution: "The configured direct route executes from WorkGraph or Context Fabric according to the node route; it does not require MCP.", configuration: ["Provider/model alias.", "Credential environment-variable name.", "Optional base URL.", "Prompt template and input variables.", "JSON output schema and retry/parse policy."], output: "Validated structured JSON in workflow context plus model usage metadata.", caution: "Direct access bypasses MCP tool governance. Keep it limited to nodes whose data and provider policy explicitly allow direct calls." },
  WORKBENCH_TASK: { key: "WORKBENCH_TASK", label: "Workbench Task", category: "agent", summary: "Opens a guided workbench stage for richer agent and human collaboration.", whenToUse: "Use for story intake, design review, or co-work stages that need a visual cockpit.", execution: "Server creates a workbench session; the browser or desktop workbench completes the stage.", configuration: ["Stage/session label.", "Agent or prompt profile.", "Required questions and artifacts.", "Human review and completion policy."], output: "Workbench answers, artifacts, decisions, and stage completion receipt.", caution: "Pass workflowInstanceId, workflowNodeId, WorkItem, story, and repository context when launching the workbench." },
  DECISION_GATE: { key: "DECISION_GATE", label: "Decision Gate", category: "flow", summary: "Evaluates one condition and selects exactly one outgoing path.", whenToUse: "Use for mutually exclusive outcomes such as APPROVE versus SEND_BACK.", execution: "Server-side; evaluates immediately from workflow context.", configuration: ["Condition expression.", "True and false edge labels.", "Fallback behavior when a value is missing."], output: "One selected outgoing edge and the evaluated condition.", caution: "Make sure upstream nodes write the field used by the condition; missing values should have an explicit false path." },
  INCLUSIVE_GATEWAY: { key: "INCLUSIVE_GATEWAY", label: "Inclusive Gateway", category: "flow", summary: "Activates every outgoing branch whose condition is true.", whenToUse: "Use for non-exclusive actions where several checks or notifications can run.", execution: "Server-side; evaluates edge conditions and may activate multiple paths.", configuration: ["Conditions on outgoing edges.", "Optional default path."], output: "Zero or more activated branches.", caution: "If no condition matches, the workflow can appear stuck unless a default path is defined." },
  EVENT_GATEWAY: { key: "EVENT_GATEWAY", label: "Event Gateway", category: "flow", summary: "Models first-to-fire event routing between signal and timer branches.", whenToUse: "Use for a race such as approval signal versus timeout.", execution: "Runtime support is limited; prefer explicit SIGNAL_WAIT and TIMER branches until the gateway is enabled for your deployment.", configuration: ["Event branches.", "Optional global timeout.", "Correlation contract for competing signals."], output: "The first eligible event branch wins and other branches are cancelled.", caution: "This is different from an inbound WorkItem EVENT trigger. Check Operations readiness before relying on it." },
  PARALLEL_FORK: { key: "PARALLEL_FORK", label: "Parallel Fork", category: "flow", summary: "Starts independent outgoing branches concurrently.", whenToUse: "Use when design, security, and test preparation can happen at the same time.", execution: "Server-side; creates multiple active branch executions.", configuration: ["Branch labels.", "Optional expected branch count."], output: "Multiple active branches sharing the parent context.", caution: "Use Parallel Join or an explicit completion policy before consuming all branch results." },
  PARALLEL_JOIN: { key: "PARALLEL_JOIN", label: "Parallel Join", category: "flow", summary: "Waits until all required parallel branches complete.", whenToUse: "Use before a release or synthesis step that needs every branch result.", execution: "Server-side; remains ACTIVE until expected branches arrive.", configuration: ["Expected branch count.", "Merge strategy for branch outputs."], output: "A merged context after all branches complete.", caution: "A missing or failed branch blocks the join; add Error Catch or a defined branch failure policy." },
  FOREACH: { key: "FOREACH", label: "For Each", category: "flow", summary: "Repeats a branch once for every item in a context collection.", whenToUse: "Use to validate files, work items, test cases, or documents individually.", execution: "Server-side; sequential or bounded parallel iterations.", configuration: ["Collection path.", "Item variable name.", "Parallel flag.", "Maximum concurrency."], output: "Per-item outputs and an iteration summary.", caution: "Keep concurrency bounded and define behavior for an empty collection." },
  CALL_WORKFLOW: { key: "CALL_WORKFLOW", label: "Sub-workflow", category: "flow", summary: "Starts a reusable child workflow and waits for its result.", whenToUse: "Use to package a repeated governance or delivery sequence.", execution: "Server-side; creates a child workflow instance linked to the parent.", configuration: ["Child workflow template ID.", "Version or release channel.", "Input and output mappings."], output: "Child result, child run id, and linked evidence.", caution: "Avoid recursive templates and define a timeout for child runs." },
  SET_CONTEXT: { key: "SET_CONTEXT", label: "Set Context", category: "data", summary: "Writes literal or mapped values into the workflow context.", whenToUse: "Use to normalize incoming events, compute flags, or prepare prompt variables.", execution: "Server-side; completes immediately.", configuration: ["Context path assignments.", "Literal JSON values or {{ references }}.", "Overwrite policy."], output: "Updated workflow context visible to downstream nodes.", caution: "Use stable names such as workItem.workId and verification.verdict so later conditions remain readable." },
  DATA_SINK: { key: "DATA_SINK", label: "Data Sink", category: "data", summary: "Persists a result to an artifact, database event, or configured connector.", whenToUse: "Use when a result must outlive the run or be consumed by another system.", execution: "Server-side or connector target depending on sink configuration.", configuration: ["Sink kind: ARTIFACT, DB_EVENT, or CONNECTOR.", "Artifact type/title/content mapping.", "Connector and operation.", "Event name and payload."], output: "Persisted artifact, event, or connector receipt.", caution: "Do not put transport secrets in node config; event bus credentials stay in environment configuration." },
  CONSUMABLE_CREATION: { key: "CONSUMABLE_CREATION", label: "Create Artifact", category: "data", summary: "Creates a typed, versioned deliverable for review or downstream use.", whenToUse: "Use for design documents, test evidence, release notes, reports, and other durable outputs.", execution: "Server-side; stores the artifact and optionally pauses for approval.", configuration: ["Artifact type and title.", "Content or source context path.", "Version.", "Requires approval flag."], output: "Artifact id, content metadata, and evidence receipt.", caution: "Use this before Git Push when the run must show which design or evidence was checked." },
  WORK_ITEM: { key: "WORK_ITEM", label: "Work Item", category: "data", summary: "Creates or updates the business work item that anchors a run.", whenToUse: "Use when a workflow should be traceable to a story, incident, request, or external identifier.", execution: "Server-side; creates or attaches a WorkItem using capability and routing policy.", configuration: ["WorkItem type.", "Work id/correlation key.", "Title and description mappings.", "Capability and routing mode."], output: "WorkItem id, work code, status, and workflow linkage.", caution: "Inbound event triggers can create WorkItems before the workflow starts; do not duplicate them inside the graph without a dedupe key." },
  TOOL_REQUEST: { key: "TOOL_REQUEST", label: "Tool Request", category: "integration", summary: "Invokes a registered tool under capability, grant, and policy controls.", whenToUse: "Use for Git, Jira, HTTP APIs, repository operations, search, or other governed actions.", execution: "Usually Runtime Bridge → MCP; server tools may execute in the platform.", configuration: ["Tool and action.", "Input mappings.", "Risk level and approval policy.", "Required capability scope."], output: "Tool response, invocation receipt, and optional artifact changes.", caution: "The tool registry and runtime must both be ready. Mutating tools may require a short-lived Tool Grant." },
  RUN_PYTHON: { key: "RUN_PYTHON", label: "Run Python", category: "integration", summary: "Runs a bounded Python task in the configured sandbox.", whenToUse: "Use for deterministic transforms, validation scripts, or formal checks with approved dependencies.", execution: "Sandbox runner or configured execution location; never assume host filesystem access.", configuration: ["Script or code input.", "Input/output mappings.", "Timeout and resource limits.", "Artifact paths."], output: "stdout/stderr, exit code, structured output, and execution receipt.", caution: "Treat code as untrusted. Use the sandbox and keep secrets out of command strings." },
  GIT_PUSH: { key: "GIT_PUSH", label: "Git Push", category: "integration", summary: "Publishes approved repository changes to the configured remote.", whenToUse: "Use at the end of a governed change flow after design, tests, and approvals.", execution: "Runtime Bridge/MCP runtime with the repository token and workspace.", configuration: ["Capability/repository binding.", "Branch policy.", "Commit and push policy.", "Required approval or governance gate."], output: "Commit SHA, remote, branch, push receipt, and failure details.", caution: "An ACTIVE runtime and valid repository credentials are required. A failed push should be handled by Error Catch or a human retry step." },
  CREATE_BRANCH: { key: "CREATE_BRANCH", label: "Create Branch", category: "integration", summary: "Creates or selects the isolated work branch for a WorkItem.", whenToUse: "Use before code-changing agent, tool, or workbench stages that must not modify the base branch.", execution: "Runtime Bridge/MCP runtime using the repository associated with the capability.", configuration: ["Base branch.", "Work branch name or naming pattern.", "Repository/capability binding.", "Clone/workspace policy."], output: "Branch name, repository state, and branch creation receipt.", caution: "A missing linked repository or Git token blocks this node. Verify the capability has an ACTIVE repository grant before launch." },
  RAISE_PR: { key: "RAISE_PR", label: "Raise Pull Request", category: "integration", summary: "Opens a pull request from the run branch after changes are ready.", whenToUse: "Use after Git Push and required governance/approval gates have passed.", execution: "Runtime Bridge/MCP runtime with repository provider credentials.", configuration: ["Base branch.", "PR title and body templates.", "Reviewers or teams.", "Labels and draft flag.", "Required evidence links."], output: "Pull request URL, number, branch pair, and creation receipt.", caution: "This node cannot open a useful PR without a pushed commit. Handle NO_COMMIT_TO_PUSH and provider permission errors explicitly." },
  CUSTOM: { key: "CUSTOM", label: "Custom Node", category: "integration", summary: "Runs a registered custom node type with its own metadata and configuration schema.", whenToUse: "Use when a reusable platform extension cannot be expressed by the built-in node types.", execution: "Depends on the custom node type's runtime base and execution location.", configuration: ["Custom node type key.", "Versioned metadata/schema.", "Inputs and outputs.", "Execution location and timeout.", "Owner and failure policy."], output: "The custom node's declared output and execution receipt.", caution: "Register and version the custom type before using it. Unknown custom types should fail validation before a workflow is published." },
  GOVERNANCE_GATE: { key: "GOVERNANCE_GATE", label: "Governance Gate", category: "governance", summary: "Checks documents, artifacts, code, standards, or combinations before allowing progress.", whenToUse: "Use for design review, Git diff validation, standards, test evidence, security, or release checks.", execution: "Server-side with optional Z3/formal-verifier and human review; hard gates block, soft gates warn.", configuration: ["Gate mode: HARD, SOFT, or MANUAL.", "Input documents/artifacts/code paths.", "Standards or rule source.", "Optional formal verifier.", "Evidence event and failure route."], output: "Pass/warn/block verdict, findings, evidence artifact, and trace correlation.", caution: "Make the evidence inputs explicit. A gate without inputs can only report configuration failure." },
  VERIFIER: { key: "VERIFIER", label: "Verifier", category: "governance", summary: "Runs a verifier agent against supplied documents and returns a structured decision.", whenToUse: "Use for document validation, design conformance, policy checks, or formalization prechecks.", execution: "Agent/runtime or direct LLM route based on its profile and node configuration.", configuration: ["Verifier agent/profile.", "Read-only URL or document skill.", "Input document mappings.", "Output schema: verdict, confidence, findings.", "Human review policy."], output: "Structured verification result and evidence document.", caution: "Keep verifier skill sources immutable or provider-locked when the verifier must be independent of the workflow author." },
  EVAL_GATE: { key: "EVAL_GATE", label: "Eval Gate", category: "governance", summary: "Compares an output against evaluation criteria or test cases.", whenToUse: "Use for quality, regression, safety, or model-output evaluation before promotion.", execution: "Server-side evaluator or runtime-backed evaluator according to configuration.", configuration: ["Evaluator/profile.", "Dataset or test case source.", "Thresholds.", "Pass/fail policy and evidence output."], output: "Scores, failed cases, pass/fail decision, and evaluation evidence.", caution: "Store the evaluator version and dataset version so the result is reproducible." },
  POLICY_CHECK: { key: "POLICY_CHECK", label: "Policy Check", category: "governance", summary: "Evaluates a named platform policy before continuing.", whenToUse: "Use for spending, residency, data handling, access, or release policy decisions.", execution: "Server-side policy engine; typically completes immediately.", configuration: ["Policy name or id.", "Input context paths.", "On failure: BLOCK, WARN, or LOG."], output: "Policy decision, reasons, and audit event.", caution: "Use BLOCK for enforceable controls; WARN only when the business explicitly accepts continued execution." },
  EVENT_EMIT: { key: "EVENT_EMIT", label: "Event Emit", category: "integration", summary: "Publishes a status or business event after a workflow stage.", whenToUse: "Use to notify another service about received, approved, rejected, or completed work.", execution: "Server outbox first; optional Kafka, SQS, SNS, AMQP, or event bus delivery.", configuration: ["Event name.", "Transport.", "Subject and correlation ids.", "Payload mapping.", "Retry/dead-letter policy."], output: "Outbox record, delivery attempts, and event receipt.", caution: "Publishing an event does not automatically start another workflow unless a matching inbound trigger exists." },
  SIGNAL_WAIT: { key: "SIGNAL_WAIT", label: "Signal Wait", category: "timing", summary: "Pauses until a named signal is delivered to this workflow instance.", whenToUse: "Use for an external callback, customer confirmation, or asynchronous completion.", execution: "Server-side; remains ACTIVE until a matching signal arrives or timeout policy fires.", configuration: ["Signal name.", "Correlation key.", "Timeout or expiry behavior.", "Payload destination."], output: "Signal payload in context and resumed execution.", caution: "Document the signal contract and correlation key for the producer; otherwise signals can wake the wrong run or none at all." },
  SIGNAL_EMIT: { key: "SIGNAL_EMIT", label: "Signal Emit", category: "timing", summary: "Sends a named signal to waiting workflow instances.", whenToUse: "Use for inter-workflow coordination or external callback handoff.", execution: "Server-side; emits and continues.", configuration: ["Signal name.", "Correlation key.", "Payload path."], output: "Signal delivery receipt and downstream wake-ups.", caution: "Signals are not durable business events; use Event Emit when an external system needs a replayable record." },
  TIMER: { key: "TIMER", label: "Timer", category: "timing", summary: "Pauses a path for a duration or until a specific time.", whenToUse: "Use for retries, escalation windows, rate limits, and scheduled follow-up.", execution: "Server scheduler; remains ACTIVE until the timer fires.", configuration: ["Duration such as 30s, 5m, or 2h.", "Duration in milliseconds.", "Absolute ISO timestamp.", "Missed-timer policy."], output: "Timer-fired receipt and resumed execution.", caution: "Timers require the scheduler to be healthy; inspect Operations when a timer remains ACTIVE beyond its due time." },
  ERROR_CATCH: { key: "ERROR_CATCH", label: "Error Catch", category: "flow", summary: "Receives a failure from an upstream node and starts a recovery path.", whenToUse: "Use around network calls, LLM calls, Git operations, and other recoverable work.", execution: "Server-side; activates from an ERROR_BOUNDARY edge.", configuration: ["Error code filter, or catch all.", "Context path for error details.", "Recovery and escalation mapping."], output: "Normalized error context and a recovery path.", caution: "A normal sequential edge does not catch failure; connect the failing node using an ERROR_BOUNDARY edge." },
};

export const GUIDE_NODE_ORDER = [
  "START", "END", "HUMAN_TASK", "APPROVAL", "AGENT_TASK", "DIRECT_LLM_TASK", "WORKBENCH_TASK",
  "DECISION_GATE", "INCLUSIVE_GATEWAY", "EVENT_GATEWAY", "PARALLEL_FORK", "PARALLEL_JOIN", "FOREACH", "CALL_WORKFLOW",
  "SET_CONTEXT", "DATA_SINK", "CONSUMABLE_CREATION", "WORK_ITEM", "TOOL_REQUEST", "RUN_PYTHON", "CREATE_BRANCH", "GIT_PUSH", "RAISE_PR",
  "GOVERNANCE_GATE", "VERIFIER", "EVAL_GATE", "POLICY_CHECK", "EVENT_EMIT", "SIGNAL_WAIT", "SIGNAL_EMIT", "TIMER", "ERROR_CATCH", "CUSTOM",
] as const;

export const GUIDE_CATEGORIES: Array<{ key: GuideNode["category"]; label: string }> = [
  { key: "flow", label: "Flow and branching" },
  { key: "human", label: "Human decisions" },
  { key: "agent", label: "Agents and models" },
  { key: "data", label: "Context and artifacts" },
  { key: "integration", label: "Tools and integrations" },
  { key: "governance", label: "Governance and verification" },
  { key: "timing", label: "Events and timing" },
];

export function guideNode(type: string | null | undefined): GuideNode {
  const key = String(type ?? "").toUpperCase();
  return GUIDE_NODES[key] ?? {
    key,
    label: key ? key.replaceAll("_", " ") : "Workflow node",
    category: "flow",
    summary: "A workflow node with no guide entry yet.",
    whenToUse: "Review the node type metadata before publishing.",
    execution: "Depends on the node implementation and execution location.",
    configuration: ["Review the node configuration JSON and runtime validation response."],
    output: "The node runtime result or an explicit configuration error.",
    caution: "Do not publish an undocumented custom node without an owner and failure policy.",
  };
}
