import { Router } from 'express'
import { z } from 'zod'
import { validate } from '../../middleware/validate'
import { completeIndependentVerification, getIndependentVerification, listCodeImpact, listGroundingEvidence, listIndependentVerifications, recordCodeImpact, recordGroundingEvidence, requestIndependentVerification, startIndependentVerification } from './verification.service'

export const verificationRouter: Router = Router()

const requestSchema = z.object({ instanceId: z.string().uuid().optional(), nodeId: z.string().uuid().optional(), workItemId: z.string().uuid().optional(), commitSha: z.string().max(200).optional(), environment: z.string().max(200).optional(), command: z.string().min(1).max(2000) })
verificationRouter.get('/', async (req, res, next) => { try { res.json(await listIndependentVerifications(typeof req.query.instanceId === 'string' ? req.query.instanceId : undefined)) } catch (err) { next(err) } })
verificationRouter.post('/', validate(requestSchema), async (req, res, next) => { try { res.status(201).json(await requestIndependentVerification({ ...req.body, actorId: req.user!.userId })) } catch (err) { next(err) } })
verificationRouter.get('/grounding', async (req, res, next) => { try { res.json(await listGroundingEvidence(typeof req.query.instanceId === 'string' ? req.query.instanceId : undefined, typeof req.query.nodeId === 'string' ? req.query.nodeId : undefined)) } catch (err) { next(err) } })
verificationRouter.post('/grounding', validate(z.object({ instanceId: z.string().uuid().optional(), nodeId: z.string().uuid().optional(), agentRunId: z.string().uuid().optional(), sourceType: z.string().min(1), sourceUri: z.string().max(2000).optional(), contentHash: z.string().max(200).optional(), influenceScore: z.number().min(0).max(1).optional(), outcome: z.string().max(80).optional(), feedback: z.record(z.unknown()).optional() })), async (req, res, next) => { try { res.status(201).json(await recordGroundingEvidence(req.body)) } catch (err) { next(err) } })
verificationRouter.get('/code-impact', async (req, res, next) => { try { res.json(await listCodeImpact(typeof req.query.instanceId === 'string' ? req.query.instanceId : undefined, typeof req.query.commitSha === 'string' ? req.query.commitSha : undefined)) } catch (err) { next(err) } })
verificationRouter.post('/code-impact', validate(z.object({ instanceId: z.string().uuid().optional(), nodeId: z.string().uuid().optional(), workItemId: z.string().uuid().optional(), commitSha: z.string().max(200).optional(), query: z.string().max(1000).optional(), provider: z.string().max(100).optional(), files: z.array(z.unknown()).optional(), callGraph: z.record(z.unknown()).optional(), matches: z.array(z.unknown()).optional(), riskScore: z.number().min(0).max(100).optional() })), async (req, res, next) => { try { res.status(201).json(await recordCodeImpact({ ...req.body, actorId: req.user!.userId })) } catch (err) { next(err) } })
verificationRouter.get('/:id', async (req, res, next) => { try { res.json(await getIndependentVerification(req.params.id)) } catch (err) { next(err) } })
verificationRouter.post('/:id/start', async (req, res, next) => { try { res.json(await startIndependentVerification(req.params.id, req.user!.userId)) } catch (err) { next(err) } })
const completeSchema = z.object({ status: z.enum(['PASSED', 'FAILED', 'CANCELLED']), result: z.record(z.unknown()).optional(), testSummary: z.record(z.unknown()).optional(), coverage: z.record(z.unknown()).optional(), findings: z.array(z.object({ filePath: z.string().optional(), ruleKey: z.string().optional(), severity: z.string().optional(), message: z.string().min(1), evidence: z.record(z.unknown()).optional() })).optional() })
verificationRouter.post('/:id/complete', validate(completeSchema), async (req, res, next) => { try { res.json(await completeIndependentVerification(req.params.id, req.user!.userId, req.body)) } catch (err) { next(err) } })
